---
# tasks file for analysis
- name: Check if the folder exists
  stat: path={{workspace}}
  register: dir_flag

- name: Delete street-signal if exists
  become: yes
  file: path={{workspace}} state=absent
  when: dir_flag.stat.exists == true

- name: Copy input files images from local to master
  copy: src={{ item }} dest={{test_images}}
  with_fileglob:
     - files/test_data/images/*
  when: dir_flag.stat.exists == false

- name: Copy stop sign classifier from local to master
  copy: src={{ item }} dest={{classifier_dir}}
  with_fileglob:
     - files/classifier/*.*
  when: dir_flag.stat.exists == false

