---
# vars file for suunni.cmd5
python_packages:
          - python-setuptools
          - python-pip
          - expect
          - build-essential
          - libpam-umask
          - libssl-dev
          - libffi-dev
          - python-dev
          - libncurses-dev
          - libreadline-gplv2-dev
          - libncursesw5-dev
          - libsqlite3-dev
          - tk-dev
          - libgdbm-dev
          - libc6-dev
          - libbz2-dev

pip_packages:
          - pycrypto
          - virtualenv
          - virtualenvwrapper
          - cryptography
          - httplib2



opencv_dependencies:
          - cmake
          - git
          - libgtk2.0-dev 
          - pkg-config
          - libavcodec-dev
          - libavformat-dev
          - libswscale-dev

opencv:


vm_home: "~/"
cm_path: "/usr/local/bin/cm"
rsa_pub_path: "/.ssh/id_rsa"
key_path: "/.ssh/id_rsa.pub"
python_path: "/usr/bin/python"
vm_user_name: "cc"
cm_user_name: "tg837246"

cmd5repository: "https://github.com/cloudmesh/cloudmesh.cmd5.git"
tmp: "/tmp/cmd5/"
signrepository: "https://github.com/cloudmesh/cloudmesh.sign.git" 

